### ISSUE TITLE
下载功能无法使用

### ISSUE THREAD

**Issue by oweaF** [Tsuk1ko/nhentai-helper#1]
chrome：76.0.3809.132
Tampermonkey：4.8.41
script：2.0.0
具体表现为设置多少线程就卡几张图片
![image](https://user-images.githubusercontent.com/25154231/63823136-570fd700-c985-11e9-905f-1b56e6a2cec0.png)
实际上我也没看到有nhentai相关的数据传输

**Comment by Tsuk1ko** [comment]
@oweaF 请看一下 console 有什么报错

**Comment by oweaF** [comment]
console什么东西都没有

**Comment by oweaF** [comment]
![image](https://user-images.githubusercontent.com/25154231/63828519-5ed97680-c999-11e9-908a-255ca0ac4988.png)
一闪而过的信息，接着console就空了

**Comment by Tsuk1ko** [comment]
哦对，nhentai 有反调试措施会自动清 console

你先在 console 里执行`console.clear=()=>{}`，然后开始下载

会出现很多`<div></div>`的输出，不用管他，看红色 error

**Comment by Tsuk1ko** [comment]
> ![image](https://user-images.githubusercontent.com/25154231/63828519-5ed97680-c999-11e9-908a-255ca0ac4988.png)
> 一闪而过的信息，接着console就空了

行，这个也行，等我下班回家看看

**Comment by Tsuk1ko** [comment]
是只在详情页面会这样么，列表页直接下载有没有问题

**Comment by oweaF** [comment]
> 哦对，nhentai 有反调试措施会自动清 console
> 
> 你先在 console 里执行`console.clear=()=>{}`，然后开始下载
> 
> 会出现很多`<div></div>`的输出，不用管他，看红色 error

![image](https://user-images.githubusercontent.com/25154231/63828766-21291d80-c99a-11e9-9972-f962487ad7f6.png)

**Comment by oweaF** [comment]
> 是只在详情页面会这样么，列表页直接下载有没有问题

在列表页面下载没问题

**Comment by oweaF** [comment]
nhentai更新了下详情页的UI，又不能用了
