### ISSUE TITLE
能否添加自动重试功能

### ISSUE THREAD

**Issue by Holo233** [Tsuk1ko/nhentai-helper#12]
在网络不太流畅的时候（大概），总是会反复出现是否重试的按钮，能否设置自动重试，以及重复队列那个功能自动取消下载。

**Comment by Tsuk1ko** [comment]
> 以及重复队列那个功能自动取消下载

这个意思是发现重复的时候不再询问你，直接跳过吗

**Comment by Holo233** [comment]
是的，或者在脚本页直接设置0（默认直接跳过），1不跳过继续下载；重试按钮同理。下比较多的本子的时候总是容易出现这俩问题，梯子换节点也不好使。
