### ISSUE TITLE
语言过滤器问题

### ISSUE THREAD

**Issue by bai12123** [Tsuk1ko/nhentai-helper#13]
大佬你好，感谢你的脚本让我能够方便地浏览nhentai，我在使用过程中发现一些小bug，以及有一个小请求，希望能得到你的帮助

1.语言过滤器选择中文后，进入某漫画详情页，再从此处选择某标签或者选择作者进入二级菜单，语言过滤器并没有记住中文选择

2.由于安装过多的nhentai脚本，且某些脚本只会用到某一个功能，我想将其整合为一个脚本为个人所用。对于nhentai-helper，语言过滤器十分好用，我想将这个功能代码单独提取出来，奈何水平有限无法做到（文科生），请问大佬能够帮忙提取一下吗？无论怎样，都先谢谢大佬了。

**Comment by Tsuk1ko** [comment]
1. 设计如此，语言过滤器设置仅储存在 session 中，即只在当前标签页内有效
2. 这个只能靠你自己了，我没有理由把它们单独提出来
