### ISSUE TITLE
firefox 标签页崩溃

### ISSUE THREAD

**Issue by caoli5288** [Tsuk1ko/nhentai-helper#14]
https://nhentai.net/g/167573/

下载这个就崩溃，试了十几次了，firefox。

**Comment by Tsuk1ko** [comment]
可能是内存不足

不过按理来说一般人应该够的吧……

我用 chrome 下这种200多页的单行本没有问题

**Comment by caoli5288** [comment]
200+页的下过很多，但这个100%崩溃，试了几十次了，你试试呢？

是在compressing阶段崩溃的。

**Comment by Tsuk1ko** [comment]
chrome 试过了没事，firefox 确实在会崩

可能是因为这个单行本真的很大，每张图都有 3MB 左右，整本有 700+MB，现在一般 200+ 页的也就 100+MB

一共 224 张，压到快结束就崩了，这个应该是 firefox 的问题，我这边就无能为力了……

![image](https://user-images.githubusercontent.com/24877906/155362319-814da9c9-a1ac-4bad-acad-2da90ef2e25d.png)

**Comment by caoli5288** [comment]
不是很懂js，有支持流式压缩的js库嘛

**Comment by Tsuk1ko** [comment]
跟流式关系不大……最终都要拿到 Buffer 生成 Blob 然后才能下载，避免不了要消耗大量内存的

**Comment by Tsuk1ko** [comment]
> Edit: 后来发现有流式实现 [StreamSaver.js](https://github.com/jimmywarting/StreamSaver.js)，不过这个方法有点黑科技，有时间研究一下能不能配合 JSZip 用

喜报：实现了流式压缩与下载

悲报：在 firefox 上由于不明原因无法使用

![image](https://user-images.githubusercontent.com/24877906/185652613-f6315b70-d2ea-4438-bd42-032777c30065.png)

**Comment by caoli5288** [comment]
评价为：寄
