### ISSUE TITLE
无法下载最后一页

### ISSUE THREAD

**Issue by uHioVK** [Tsuk1ko/nhentai-helper#17]
我不知道为什么但是本子最后一页总是不见
如果是有意设置建议加个可选项

**Comment by uHioVK** [comment]
总之要是本子后面没有翻译者添加页或者尾页就容易漏内容

**Comment by Tsuk1ko** [comment]
没有这个设计，是完整下载的，我自己也没有遇过这个问题

看下 console 有没有报错

这个问题是必现还是偶现

**Comment by uHioVK** [comment]
电脑上测试没有问题，控制台未报错，好像之前手机上(kiwi browser)会偶然有问题，之后我再看一下
