### ISSUE TITLE
经常下载出错无法取消或删除

### ISSUE THREAD

**Issue by myzzh5** [Tsuk1ko/nhentai-helper#18]
![4DM )6M~$V2$40K0_W{8BBL](https://user-images.githubusercontent.com/39124372/180768978-33d479f4-160e-46f3-9dc1-1f2a3c887ccd.png)
![$SVMCAR}BGCHHTM}M7NPYN8](https://user-images.githubusercontent.com/39124372/180770199-7780dc71-124c-41db-8d8b-e00ccc7d30ab.png)
如图，经常会出现下载打包100%后卡住不动的情况
此时无法取消或删除任务，并且出现这种情况的时候刷新也无法解决，只能完全关闭当前标签页
下载过程中的任务无法单击一次就取消，需要连续不断的点×直至任务取消

**Comment by Tsuk1ko** [comment]
打包卡住的情况看看 console 有没有报错

下载中任务点击取消不会立即消失是正常的，需要等待已经开始下载的图片下载结束才能完全取消，实际上点一次就可以，这个确实可以增加个视觉反馈

**Comment by myzzh5** [comment]
如果可以的话最好还是能加一个所有阶段都能取消的功能，这样能避免出现100%卡住之后还要另开一个标签页重新下载的问题，因为如果出现报错的情况，刷新无法解决的情况下，也能通过取消报错的下载项

**Comment by Tsuk1ko** [comment]
压缩一旦开始无法取消，且压缩卡100%是不正常的情况，一旦进入压缩流程，这个本子就不会再阻塞其他本子的下载进度，取消压缩并不能解决问题，最好能提供错误日志定位问题原因

在 nhentai 页面控制台执行 `localStorage.setItem('NHENTAI_HELPER_DEBUG',1)` 然后刷新，可以阻止 nhentai 不停清除控制台，如果下次复现的话可以提供下日志

**Comment by myzzh5** [comment]
![Uploading QQ图片20220731184706.png…]()

**Comment by myzzh5** [comment]
![QQ图片20220731184706](https://user-images.githubusercontent.com/39124372/182022611-9df48cc0-39fe-4fd2-a9e4-8668276c43b3.png)

**Comment by Tsuk1ko** [comment]
看起来是内存太小导致的……

**Comment by myzzh5** [comment]
![QQ图片20220731185427](https://user-images.githubusercontent.com/39124372/182022796-05fdfadd-9a4d-4846-9c3c-033e58f0d6eb.png)

**Comment by Tsuk1ko** [comment]
检查下你的 chrome 是否装成32位的了，确实是64位的话就不清楚原因了

**Comment by Tsuk1ko** [comment]
那不清楚原因了……

**Comment by Tsuk1ko** [comment]
如果你一个个本子慢慢下会出现这种情况吗

**Comment by myzzh5** [comment]
一个一个下没出现过，加入下载列表才能碰到这种情况，而且并不是同时很多本子开始压缩的时候才会出现

**Comment by myzzh5** [comment]
![QQ图片20220731190151](https://user-images.githubusercontent.com/39124372/182023044-5b5ecc31-8365-48d3-ba64-65160c1b6be7.png)
这个问题只要出现了一次，下面的列表就跟传染了一样，很快就会出现第二个，但并不一定是连续出现

**Comment by Tsuk1ko** [comment]
请尝试下新版本是否有改善

**Comment by gylidian** [comment]
> 请尝试下新版本是否有改善

@Tsuk1ko  出现同样情况

<img width="345" alt="image" src="https://user-images.githubusercontent.com/30214981/182039828-5d692f3b-b632-448c-a720-f4198660b802.png">

<img width="582" alt="image" src="https://user-images.githubusercontent.com/30214981/182039809-c8f01363-a139-4cd1-ac2c-012f58c37b60.png">

**Comment by Tsuk1ko** [comment]
@gylidian 看了下隔壁的解决方法也只是让你分页下载或者不要一次性下载太多而已，看起来没有什么治本的方法

挺奇怪的，我自己一直没出过这个问题，即使有时候同时在压缩七八本甚至里面还有几个一两百页的单行本

我只能试试加一个低内存消耗选项，同一时间只处理一个本子的下载和压缩，尽量减少内存消耗了

**Comment by gylidian** [comment]
> @gylidian 看了下隔壁的解决方法也只是让你分页下载或者不要一次性下载太多而已，看起来没有什么治本的方法
> 
> 挺奇怪的，我自己一直没出过这个问题，即使有时候同时在压缩七八本甚至里面还有几个一两百页的单行本
> 
> 我只能试试加一个低内存消耗选项，同一时间只处理一个本子的下载和压缩，尽量减少内存消耗了

感谢！

**Comment by Tsuk1ko** [comment]
加了两个可能有帮助的选项，可以试试，还不行的话我也没办法了

https://github.com/Tsuk1ko/nhentai-helper/blob/296a43a3f70f77232646edaa5b94a85d0595005f/README-ZH.md?plain=1#L44-L48

取消下载的优化也完成了
