### ISSUE TITLE
#download-panel element blocks a part of image on the small display (especially on mobile phone)

### ISSUE THREAD

**Issue by waitingmoon** [Tsuk1ko/nhentai-helper#2]
![Screen-Shot-2020-03-19-at-18 41 27](https://user-images.githubusercontent.com/16256443/77053725-1b685780-6a12-11ea-8f46-8ee9d2571395.jpg)

as a above image, #download-panel element blocks a part of image, on the small display device (especially on the mobile). I guess it will happen when the viewport width is less than 1366px, so it's a better that the panel is on the another place (maybe top or bottom?) instead of the right side if your display is small.

**Comment by Tsuk1ko** [comment]
Theoretically, when the list is empty, its height is 0 and it will not be displayed.

This may be caused by rendering differences between different browsers on different platforms.

I have fixed it in v2.5.2, thanks for your report.
