### ISSUE TITLE
下载图片是怎么实现的？

### ISSUE THREAD

**Issue by Minori-ty** [Tsuk1ko/nhentai-helper#20]
没看懂代码中的下载逻辑，是爬取详情页中的图片吗？
能否做到调用下载torrent？

**Comment by Tsuk1ko** [comment]
调用 nhentai 官方 API 拿到本子信息，之后可以直接去下载在线浏览的原图

理论上可以，有库能在 web 中下载 torrent，但是 torrent 太不稳定了，所以才有这个脚本

**Comment by Minori-ty** [comment]
> 调用 nhentai 官方 API 拿到本子信息，之后可以直接去下载在线浏览的原图
> 
> 理论上可以，有库能在 web 中下载 torrent，但是 torrent 太不稳定了，所以才有这个脚本

也就是算是爬网页图吗?

**Comment by Tsuk1ko** [comment]
你觉得算那就算吧😂

**Comment by Minori-ty** [comment]
> 

好的

**Comment by Minori-ty** [comment]
> 你觉得算那就算吧😂

可以加个一键下载收藏页的所有作品到一个大zip的功能吗？

**Comment by Tsuk1ko** [comment]
没有这个打算

而且一次性压缩这么多页内存会炸的……

**Comment by Minori-ty** [comment]
> 没有这个打算
> 
> 而且一次性压缩这么多页内存会炸的……

可以用prompt让用户输入下载的页数，这样做到批量下载的功能

**Comment by Minori-ty** [comment]
阿这，我尝试遍历所有的button，然后click，完成了一页下载。谢谢你，超人
