### ISSUE TITLE
[Feature Request] 页面选项卡标题添加下载完成状态的指示器

### ISSUE THREAD

**Issue by gylidian** [Tsuk1ko/nhentai-helper#21]
- 列表页的 title 前缀添加 `[114/514]` 或 `[√]`
- 本子详情页的 title 前缀添加 `[downloading]`  或 `[√]`

**Comment by Tsuk1ko** [comment]
给 title 添加完成状态的意义是什么呢，按钮上已经有状态了

**Comment by Tsuk1ko** [comment]
噢，指的是网页标题是么

**Comment by gylidian** [comment]
> 噢，指的是网页标题是么

没及时回复，不好意思

确实

已经看到更新了

多谢
