### ISSUE TITLE
发现一个无法下载的本子

### ISSUE THREAD

**Issue by myzzh5** [Tsuk1ko/nhentai-helper#23]
![QQ图片20220802180358](https://user-images.githubusercontent.com/39124372/182349019-502a82fb-919e-40ec-8dff-19304c2754e7.png)
![QQ图片20220802180412](https://user-images.githubusercontent.com/39124372/182349050-bac7a0d9-5ac7-4ec4-ab4b-ed274b5fb52c.png)
如图下载会直接报错
本子地址：https://nhentai.net/g/155844/

**Comment by Tsuk1ko** [comment]
这本子的最后一页确实有问题

![image](https://user-images.githubusercontent.com/24877906/182383248-210366a9-d1d6-4851-81ab-00b6c9742681.png)

稍后加个跳过这种错误的页
