### ISSUE TITLE
可以设置并行下载压缩的数量吗？

### ISSUE THREAD

**Issue by Minori-ty** [Tsuk1ko/nhentai-helper#28]
要一个一个等太慢了，像一些有大内存的电脑，都不怕吃内存的。可以设置并行下载和压缩的数量吗？

**Comment by Tsuk1ko** [comment]
压缩是并行的，并行最大数量取决于你的 CPU 线程数（当然一般堆积不到这个数量，压缩比下载快多了）

下载也是多图并行的，线程数可以在设置里改

不会多个本子一起下载，因为本来单个本子下载的时候内部的图片就已经在并行下载了，多个本子一起下载没有意义，下载慢的话建议还是从代理方面找原因

**Comment by Minori-ty** [comment]
嗯，就是想并行下载多本子。。。

**Comment by Minori-ty** [comment]
> 压缩是并行的，并行最大数量取决于你的 CPU 线程数（当然一般堆积不到这个数量，压缩比下载快多了）
> 
> 下载也是多图并行的，线程数可以在设置里改
> 
> 不会多个本子一起下载，因为本来单个本子下载的时候内部的图片就已经在并行下载了，多个本子一起下载没有意义，下载慢的话建议还是从代理方面找原因

主要是js的下载都是并行下载的，然后你把下载本子的改成了串行下载把。。。

**Comment by Tsuk1ko** [comment]
啥意思……

**Comment by Minori-ty** [comment]
> 啥意思……

没，我的意思是js本身就是异步的，循环下载的话，应该都是并行下载的。是不是你做了队列处理，才变成一个本子一个本子队列下载的？

**Comment by Tsuk1ko** [comment]
是的，不然同时下好几个本子并行下几百张图就太恐怖了

**Comment by Minori-ty** [comment]
> 是的，不然同时下好几个本子并行下几百张图就太恐怖了

是的，所以我说有大内存的电脑不怕的。所以为了下载效率，是否可以开放设置可以下载的本子的数量

**Comment by Tsuk1ko** [comment]
倒不是内存够不够的问题，只是我觉得这不太好

目前没有开放这种设置的打算，一般 32 线程已经足够了，受限于代理质量更多点

要是想改高点线程数倒是可以，自行去脚本插件里点开脚本改储存了的设置

![image](https://user-images.githubusercontent.com/24877906/189640971-76a85668-d6b5-416d-830f-89f6a1584d94.png)
