### ISSUE TITLE
能否将 记录已下载的本子的本地文件 转移到不同电脑上？

### ISSUE THREAD

**Issue by 1140811911** [Tsuk1ko/nhentai-helper#30]
我能否，又应该怎样将 记录已下载的本子的本地文件 转移到不同电脑上？
感谢你的nHentai 助手（这真是件伟大的作品）希望你能回复我。

**Comment by Tsuk1ko** [comment]
谢谢，但我不太能不理解你说的话，能描述的详细一点吗

Thank you, but I can't understand what you're saying. Could you describe in more detail? English is ok.

**Comment by 1140811911** [comment]
The downloaded book will be grayed out, and a warning pop-up will appear when repeated downloads are made. Does this feature generate a local file that records the download history? I would like to be able to sync it to other computers, where should I find it.
Thank you for your reply and I'm sorry that my description caused a hindrance in our communication.

**Comment by Tsuk1ko** [comment]
Open the setting via script menu, and then you can export or import the history.

![image](https://user-images.githubusercontent.com/24877906/200160982-ee04170c-a8cf-42fb-8ecd-de2617e58891.png)

![image](https://user-images.githubusercontent.com/24877906/200160994-a48fdb97-9bed-4d03-976a-aba2d5107c36.png)

**Comment by 1140811911** [comment]
Thank you for your help and good luck blessing you
