### ISSUE TITLE
Page download.

### ISSUE THREAD

**Issue by bropines** [Tsuk1ko/nhentai-helper#33]
Is it possible to add a feature where you can download N-number of pages of a certain tag or search query?
If not, question, is there any way to either download the entire manga from the currently open page?

**Comment by Tsuk1ko** [comment]
I have no plans to add such functions at present. It's a bit inconsistent with my original intention to make this script.

But you can use js to trigger the click event of all download buttons to do that.

**Comment by bropines** [comment]
> I have no plans to add such functions at present. It's a bit inconsistent with my original intention to make this script.
> 
> But you can use js to trigger the click event of all download buttons to do that.

It's left me dumb to figure out how to do it, but thanks for the answer.

**Comment by bropines** [comment]
> > I have no plans to add such functions at present. It's a bit inconsistent with my original intention to make this script.
> > But you can use js to trigger the click event of all download buttons to do that.
> 
> It remains for me an idiot to figure out how to do this, but thank you for the answer

I (almost) made the code for the console (12 hours I sat on it).


```
let nodeList = document.querySelectorAll(".download-zip-btn") ;
nodeList=[...nodeList]
let interval = setInterval(()=>{
    var step;
    for (step = 0; step < 25; step++) {
        let currentElement = nodeList.shift();
        currentElement.click();
    }

    if (nodeList.length == 0) {
        clearInterval(interval);
    }
}, 60000);
```

**Comment by bropines** [comment]
@Tsuk1ko Is it possible to add more multithreading? At the moment it can load 1 and compress one. I would like to be able to download more than one manga at a time.

**Comment by Tsuk1ko** [comment]
> @Tsuk1ko Is it possible to add more multithreading? At the moment it can load 1 and compress one. I would like to be able to download more than one manga at a time.

In fact they are all multithreaded.

Many pages will be downloaded at the same time, you can increase the number of threads in the settings.

Compression is actually an independent queue and multithreaded, if your download speed is fast enough you can see it.

**Comment by bropines** [comment]
I probably didn't put it that way. The fact is that he loads quickly, but only one manga. that is, not in parallel. Or I have a bug. But when I download the conditional 20 manga, he starts pumping one (quickly) and only when compression begins, the second one swings

**Comment by bropines** [comment]
![browser_wkRPsbB6DF](https://user-images.githubusercontent.com/57861007/208281803-2e586eb8-3616-4959-92b7-b7a8099a6446.gif)

**Comment by Tsuk1ko** [comment]
This is correct behavior. Mangas are downloaded serially, only pages are downloaded in parallel.

**Comment by bropines** [comment]
> This is correct behavior. Mangas are downloaded serially, only pages are downloaded in parallel.

Will parallel manga loading be added?

**Comment by Tsuk1ko** [comment]
> > This is correct behavior. Mangas are downloaded serially, only pages are downloaded in parallel.
> 
> Will parallel manga loading be added?

No, they are essentially the same thing. It's actually downloading multiple pages at the same time.
