### ISSUE TITLE
能否增加 自动取消下载过的本子 的识别范围

### ISSUE THREAD

**Issue by Sweet-dream-M** [Tsuk1ko/nhentai-helper#35]
新年快乐。

在使用中注意到自动取消的识别似乎只针对一种“语言”，不知道能不能将识别的范围扩大到包含同一本书的其他语言译本。

比如下图同一语言的同一本会判定为已下载，并自动取消
![屏幕截图 2023-01-06 184535](https://user-images.githubusercontent.com/48856469/210996309-d557233b-ea67-41e3-a437-83d00769f0b1.jpg)
而对于不同语言的同一本则会重复下载
![屏幕截图 2023-01-06 184528](https://user-images.githubusercontent.com/48856469/210997159-95cdd0ef-90b3-4622-8aad-462784d51fa2.jpg)
是否能够在下载时，让图2的也能像图1一样识别并取消下载？

期待你的回复。

**Comment by Tsuk1ko** [comment]
每个本子的标题会有三种版本

![image](https://user-images.githubusercontent.com/24877906/211001457-45d9b75b-b34c-446e-86ef-84ad89d2163f.png)

目前逻辑是只根据 `japanese` 来判断，其实是经过特殊考虑，特意让大多数的不同语言、无修正、DL版之间不会被判定为同一本

针对你提出的情况，我打算加入自定义判断的设置，可以自由选择使用 `english` `japanese` `pretty`  中的一个或多个字段进行判断，这样应该能解决你的问题

但需要注意

1. 标题是上传者提交的，就算使用所有字段来判断也并不能保证能 100% 过滤掉所有相同的本子
2. 判断来源是每次下载成功后会将本子名字存到 IndexedDB 中，由于之前只存了 `japanese`，所以即使我增加了这个功能，以前的本子还是只能通过 `japanese` 来判断

**Comment by Sweet-dream-M** [comment]
感谢你

**Comment by Tsuk1ko** [comment]
先不用关闭
