### ISSUE TITLE
Option to add artist names to filename

### ISSUE THREAD

**Issue by Haregata** [Tsuk1ko/nhentai-helper#36]
Something like {{artist}}
And maybe if the doujin has more than 3 artists replace it with "various" to not clog the filename

**Comment by Tsuk1ko** [comment]
This may not work as you think. nHentai don't provide an artist field.

The only way to get the artists is to separate from the title (use regular expression) or the artists tag.

Getting from title is unstable, and the text in the artists tag is different from the real artists name.

![image](https://user-images.githubusercontent.com/24877906/212659360-1023fe55-a4ea-48c8-bc64-2d72cb2ba3c8.png)

**Comment by Tsuk1ko** [comment]
Yes, you are getting artists tag from this api.

![image](https://user-images.githubusercontent.com/24877906/212734388-57a72d0c-5453-4d67-bb6a-dd5f193cc190.png)

If you accept that the tag name is slightly different from the real artist name (e.g. lowercase), it's fine.

If there are multiple artists, how do you want to combine them, for example, separated by commas?  `a, b, c`

**Comment by Tsuk1ko** [comment]
ok
