### ISSUE TITLE
i.nhentai.net:443下载缓慢

### ISSUE THREAD

**Issue by FrostNova67204** [Tsuk1ko/nhentai-helper#37]
04.19日，从i.nhentai.net来源下载漫画变得十分缓慢（只有50-70KB）.在油猴的脚本编辑页里手动将所有的i.nhentai.net改为i3.nhentai.net后下载恢复了，不知道是不是网站本身的问题。
大大也许可以把i3.nhentai.net作为一个低速时的备选链接或者切换选项？以下是截图。
这是使用i.nhentai.net时的下载速度
![image](https://user-images.githubusercontent.com/64702722/233100835-cadee419-27aa-40e5-82f4-0fd48b634282.png)
这是使用i3.nhentai.net时的下载速度
![image](https://user-images.githubusercontent.com/64702722/233100981-38620a92-0469-4d89-8450-d09f3bef8ab1.png)

**Comment by Tsuk1ko** [comment]
不过其实他们都是 cf 的来着，理论上没差别

![image](https://user-images.githubusercontent.com/24877906/233129224-882cca1c-382e-4664-b2fc-3934799cb25c.png)

**Comment by Tsuk1ko** [comment]
不过确实后端可能有差别，到时候做个选项可以自行切换节点好了

**Comment by FrostNova67204** [comment]
感谢大佬🤤
