### ISSUE TITLE
how to setup

### ISSUE THREAD

**Issue by spiderwsx1120** [Tsuk1ko/nhentai-helper#41]
解壓縮後將[script.user]丟入Edge的擴充插件裡並開啟後，nhentai沒有出現任何改變。
想請教從安裝到設置的完整步驟。謝謝
After decompressing and throwing [script.user] into the extension plug-in of Edge and opening it, there is no change in nhentai.
Would like to ask the complete steps from installation to setup. Thanks

**Comment by Tsuk1ko** [comment]
需要先安装 [Tampermonkey](https://www.tampermonkey.net/) 或 [Violentmonkey](https://violentmonkey.github.io/) 插件

之后点击 readme 中的”从 Github Pages 安装“就会弹出安装窗口，操作下去即可

**Comment by spiderwsx1120** [comment]
問題已解決，謝謝
