### ISSUE TITLE
Language filter appearance is broken on mobile.

### ISSUE THREAD

**Issue by kyoyacchi** [Tsuk1ko/nhentai-helper#44]
The "Filter" seems to be misaligned in mobile menu.

I'm using Kiwi Browser. (Violentmonkey)
It was on the middle before the update. 
![Screenshot_20230914-215148](https://github.com/Tsuk1ko/nhentai-helper/assets/63583961/14968cb9-be2d-4508-91ce-a49cd0ee870d)

**Comment by Tsuk1ko** [comment]
fixed
