### ISSUE TITLE
[Feature Request] Replace a specific special character with a custom valid character

### ISSUE THREAD

**Issue by 0xJsoul** [Tsuk1ko/nhentai-helper#47]
An option to replace "|" the japanese/romaji and english title separator with "-" instead of making it blank like this "  " or removing the created extra spaces altogether.

for example:
[Input] English title | Romaji title ---> [Output] English title - Romaji title
(instead of it being like this "[Output] English title Romaji title" or this "[Output] English title(2 spaces)Romaji title")

not all special characters should be replace with "-" like ":" (so it would be "Title: Another title" ---> "Title Another title"), only this "|" separator should be changed.

you can use these for testing:
https://nhentai.net/g/504598/
https://nhentai.net/g/504561/
https://nhentai.net/g/257326/

**Comment by 0xJsoul** [comment]
I found a valid character "｜", replacement for "|"

**Comment by Tsuk1ko** [comment]
Now it supports title replacement.

![image](https://github.com/Tsuk1ko/nhentai-helper/assets/24877906/d196e53d-25d7-4fae-98c0-ec247a4e30ce)
