### ISSUE TITLE
[Feature Request] Display the total number of pages on the thumbnail with the download button.

### ISSUE THREAD

**Issue by 0xJsoul** [Tsuk1ko/nhentai-helper#48]
Display the (total of) pages on the thumbnail besides or below the download button, or when you hover over the download button or thumbnail it will show how many pages to download, or on the upper right side of the thumbnail.

The purpose is; so I can know without clicking it if it's a one shot or an illustration using the number of pages.
How many pages it has is unknown until you click it or go in a full page with it.

**Comment by Tsuk1ko** [comment]
A new setting "Context menu preview" has been added.

Enable it and right click on a manga to preview all information.

**Comment by Smile8848** [comment]
> 添加了新设置“上下文菜单预览”。
> 
> 启用它并右键单击漫画以预览所有信息。

大佬可以在标题旁边增加个复制按钮吗？用于复制搜索本地是否存在该文件。。

**Comment by Tsuk1ko** [comment]
> 大佬可以在标题旁边增加个复制按钮吗？用于复制搜索本地是否存在该文件。。

加了

**Comment by Smile8848** [comment]
> > 大佬可以在标题旁边增加个复制按钮吗？用于复制搜索本地是否存在该文件。。
> 
> 加了

感谢大佬！
