### ISSUE TITLE
希望改变一下命名方式

### ISSUE THREAD

**Issue by jwy090815** [Tsuk1ko/nhentai-helper#5]
现在的命名方式是1.jpg、2.jpg、3.jpg.......10.jpg、11.jpg，在电脑上显示正常，
但是在我的群晖nas或是ios上排序就会变成1.jpg、10.jpg、11.jpg、2.jpg、20.jpg......3.jpg、4.jpg，类似的排列错误，每次下好本子之后都要一个一个重新命名，
希望下载的默认文件名能变成0001.jpg、0002.jpg、0003.jpg......0010.jpg、0011.jpg类似这样的前面加几个零来避免，
插件很方便，我就指望这个插件来下本子了，希望能看到

**Comment by Tsuk1ko** [comment]
增加了一个文件名长度的设置来解决这个问题
