### ISSUE TITLE
nhentai的某些镜像站读不到图源

### ISSUE THREAD

**Issue by WiiGe** [Tsuk1ko/nhentai-helper#50]
例如:
https://nhentaiyaoi.net/
和
https://nhentai.to/

可以的话请写个指南告诉用户该如何配置自定义下载服务器和URL匹配吧, `// @match              https://nhentai.to/*`加了似乎并未起效

**Comment by Tsuk1ko** [comment]
nhentai.to 本来就在 match 里的，不用手动加匹配，获取下载地址失败是逻辑有点问题，已经修复

nhentaiyaoi.net 无法支持，跟 nhentai.net 用的不是同一套 UI，脚本不会适配这类镜像站

**Comment by WiiGe** [comment]
大佬牛逼!
