### ISSUE TITLE
Userscript has error on nhentai.website

### ISSUE THREAD

**Issue by blackheart35** [Tsuk1ko/nhentai-helper#51]
The userscript doesn't work on nhentai.website anymore. It throws this error in the console:

![grafik](https://github.com/user-attachments/assets/02bac574-7a95-4a3f-9163-f7b4c137963e)

It still worked about a week ago, so i'm not sure what changed.
nhentai.net and nhentai.to also still work.

**Comment by blackheart35** [comment]
If it helps anything, `S$` seems to refer to the variable `nativeNow` in line 819 of the userscript. In line 823 `nativeNow` gets called and that seems to cause the problem. Now i still don't understand why this only happens on nhentai.website and i'm not familiar with debugging userscripts in the browser, so it's hard for me to get deeper into it.

**Comment by blackheart35** [comment]
Ok, it seems i was a bit too quick with my last message. I tried calling `Date.now()` in my browser console both on nhentai.net and nhentai.website and somehow `Date.now()` isn't recognized on nhentai.website. So this is an issue with the website and not this userscript.

Anyway, would it be an option to polyfill this, if the issue on the site doesn't get resolved soon?
I don't want to lose the option to download from nhentai.website, since they have a lot of missing galleries from the nhentai.net purges and are way more up to date than nhentai.to.

**Comment by Tsuk1ko** [comment]
Sorry, I seem to have missed this issue.

nHentai and some of its mirror sites do replace the `Date` class and cause it doesn't have the `now()` method, but this generally (in Chrome with Tampermonkey) won't affect the script because the script is running in a sandbox environment.

Please tell me your browser and script extensions so I can test it.

**Comment by blackheart35** [comment]
I'm using Firefox and Violentmonkey. I tested it in Chrome too and had the same issue with Violentmonkey, but Tampermonkey seems to work fine.

**Comment by Tsuk1ko** [comment]
Fixed in 3.14.6
