### ISSUE TITLE
nhentai无法显示下载图标

### ISSUE THREAD

**Issue by luck-233** [Tsuk1ko/nhentai-helper#53]
网站是nhentai.xxx，在Tampermonkey已启用nHentai助手，但是无论在首页的列表，还是点进某个本子的页面，都没有显示助手脚本的下载图标（Download as zip那个图标），已经试过将脚本删除并重新安装，还是一样没有显示。
上次使用是5月份，那时可以正常使用的，能看到助手脚本的下载图标。请博主帮忙看看问题在哪，谢谢~~
![无法显示下载图标](https://github.com/user-attachments/assets/a7914496-3e75-49bd-8196-cd6e466f3cc0)

**Comment by Tsuk1ko** [comment]
由于 nhentai.xxx 网站有变化，现在元素类名等与 nhentai 官方网站不一致，脚本暂时用不了，后面有空的时候我可能会考虑适配一下

**Comment by luck-233** [comment]
> 由于 nhentai.xxx 网站有变化，现在元素类名等与 nhentai 官方网站不一致，脚本暂时用不了，后面有空的时候我可能会考虑适配一下

原来如此，感谢博主的回复\(^o^)/~
