### ISSUE TITLE
nhentai download broke down because nh adds a new picture fieltype - webp

### ISSUE THREAD

**Issue by FennyZSF** [Tsuk1ko/nhentai-helper#57]

**Comment by FennyZSF** [comment]
search for png ，add codes to run 搜寻png，添加代码

    NHentaiImgExt2["w"] = "webp";   is added

   var NHentaiImgExt = /* @__PURE__ */ ((NHentaiImgExt2) => {
        NHentaiImgExt2["j"] = "jpg";
        NHentaiImgExt2["p"] = "png";
        NHentaiImgExt2["g"] = "gif";
        NHentaiImgExt2["w"] = "webp";          
        return NHentaiImgExt2;
      })(NHentaiImgExt || {});

I dont know how to use github，comment here
我不知道怎么用github，在这里提一下

**Comment by FrostNova67204** [comment]
并且含webp图片的zip文件在导入calibre时会无法识别，在修复时希望可以增加一个将webp转码为其他格式后再打包的功能。

**Comment by Tsuk1ko** [comment]
已经支持 webp 和下载时自动转换格式，可以在设置里调整目标格式和质量，默认打开，转换为 85% jpg
