### ISSUE TITLE
[功能请求]增加压缩文件名特殊标识

### ISSUE THREAD

**Issue by Smile8848** [Tsuk1ko/nhentai-helper#58]
![chrome_275](https://github.com/user-attachments/assets/5fb1ebcc-2647-462f-9c75-f737d23a122b)
有的本子英文标题有注明机翻，但日文标题中没有，可以压缩文件名时能带上机翻这类的标识吗。。

**Comment by Tsuk1ko** [comment]
增加了个自定义文件名函数的设置，你可以写入这段代码来达到效果

```js
if (gallery.title.english?.includes('机翻') && !filename.includes('机翻')) {
  const extIndex = filename.lastIndexOf('.');
  const name = filename.substring(0, extIndex);
  const ext = filename.substring(extIndex);
  return `${name}${name.endsWith(']') ? '' : ' '}[机翻]${ext}`;
}
return filename;
```

**Comment by Smile8848** [comment]
> 增加了个自定义文件名函数的设置，你可以写入这段代码来达到效果
> 
> ```js
> if (gallery.title.english?.includes('机翻') && !filename.includes('机翻')) {
>   const extIndex = filename.lastIndexOf('.');
>   const name = filename.substring(0, extIndex);
>   const ext = filename.substring(extIndex);
>   return `${name}${name.endsWith(']') ? '' : ' '}[机翻]${ext}`;
> }
> return filename;
> ```

太强了，感谢大佬！！
