### ISSUE TITLE
[故障？]下载反复重试

### ISSUE THREAD

**Issue by Smile8848** [Tsuk1ko/nhentai-helper#59]
userscript.html?name=nHentai-Helper.user.js&id=1af1cd4d-7ce5-4ff3-9c5f-cd2c4634516b:256 [nhentai-helper] Request error, retry 404 https://i7.nhentai.net/galleries/3147605/25.webp {readyState: 4, responseHeaders: 'content-length: 548\r\ncontent-type: text/html\r\ndate: Sat, 07 Dec 2024 03:03:50 GMT\r\nserver: nginx\r\n', finalUrl: 'https://i7.nhentai.net/galleries/3147605/25.webp', status: 404, statusText: '', …}

似乎下载不了了，更换了节点依旧如此。

**Comment by Smile8848** [comment]
> userscript.html?name=nHentai-Helper.user.js&id=1af1cd4d-7ce5-4ff3-9c5f-cd2c4634516b:256 [nhentai-helper] Request error, retry 404 https://i7.nhentai.net/galleries/3147605/25.webp {readyState: 4, responseHeaders: 'content-length: 548\r\ncontent-type: text/html\r\ndate: Sat, 07 Dec 2024 03:03:50 GMT\r\nserver: nginx\r\n', finalUrl: 'https://i7.nhentai.net/galleries/3147605/25.webp', status: 404, statusText: '', …}
> 
> 似乎下载不了了，更换了节点依旧如此。

似乎是下载节点寄了，i3可以正常下载

**Comment by Tsuk1ko** [comment]
是这样，自从实装 webp 后就会有这种个别节点没有图片的情况变得很频繁，后续优化一下

**Comment by Tsuk1ko** [comment]
看了下各 cdn 之间不一致的情况还挺严重，现在节点设置加了个自动获取并且作为默认值，原先的用户首次升级上来也会自动切换到自动获取
