### ISSUE TITLE
No download buttons on nhentai.net

### ISSUE THREAD

**Issue by SiGMono** [Tsuk1ko/nhentai-helper#60]
Literally just the title, resetting or uninstalling the nhentai helper and reinstalling it from sleazyfork did not work either.

**Comment by Tsuk1ko** [comment]
Make sure you use this script on PC and not on mobie device.

Please provide what you are using:

- Browser and its version
- Userscript manager
- Operating system

And any errors about userscript in browser devtools console, if exist.
