### ISSUE TITLE
Select page (feature request)

### ISSUE THREAD

**Issue by venya-san** [Tsuk1ko/nhentai-helper#7]
Coud you add something that sort the images number to something like this: 001.png , 002.png, ... ,100.png and so on. (Since I'm using ComicRack to read, if the image contain one number it will mess up the file order...)

And if possible a feature that download selected images would be nice, like download: 109.png - 125.png only.

**Comment by Tsuk1ko** [comment]
First feature is already exist, see **Filename Length** setting.

Select page will be added on next version.

**Comment by venya-san** [comment]
i guess I'm dumb... not understanding that i could use that first feature like that, anyway thanks for your hardwork and I'm Iooking forward on selection page feature.

**Comment by Tsuk1ko** [comment]
Now you can specify some page ranges to download.

Ranges are separated by commas. They can be:

- a single page
- `start-end` from _start_ to _end_
- `start-` (no end) from _start_ to the last page

![](https://user-images.githubusercontent.com/24877906/123662716-4aea4e80-d868-11eb-9c11-48a4e7829cdf.png)
