### ISSUE TITLE
搭配自动翻页插件时过滤失效

### ISSUE THREAD

**Issue by ASIjacket** [Tsuk1ko/nhentai-helper#8]
如题 列表页自动翻页后 后续页面的过滤功能就失效了

我尝试
`$('#lang-filter').change()`执行时再运行一次  `$('.gallery').each()` 不完美解决(需手动触发change)，不造作者大大有没有建议 :)

**Comment by Tsuk1ko** [comment]
是什么自动翻页插件？

**Comment by ASIjacket** [comment]
比如这个
https://greasyfork.org/zh-CN/scripts/33522-super-preloaderplus-one-new
一般是 下拉到第一页最后  自动把下一页拼接到下面

**Comment by Tsuk1ko** [comment]
现在过滤和下载功能都兼容这种自动翻页了

**Comment by ASIjacket** [comment]
好耶
