### ISSUE TITLE
What url does it download from?

### ISSUE THREAD

**Issue by silembir** [Tsuk1ko/nhentai-helper#9]
Hello,

I am trying to use this script with Download Router for Chrome where based on the domain, it puts the downloaded ZIP in a specific folder.  I am using the domain nhentai.net right now but that's not working so I don't think that is the domain that this script downloads from.  Any help would be appreciated.  Thanks!

**Comment by Tsuk1ko** [comment]
ZIP will be download from a blob URL like `blob:https://nhentai.net/xxxxx`. It is created by [URL.createObjectURL()](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL).

**Comment by silembir** [comment]
Thanks for the quick response!
